export const CONSTANT = {
    SUSTAINABILITY: "Sustainability",
    GAMIFICATION: "Gamification",
    ACCELARATE: "Accelarate your sustainability journey !!",
    STORE: "Store Manager Details:",
    STORMAN_NAME: "Store Manager's Name",
    STOREMAN_NAMEVALID: "  Please enter the Manager's name (required**)",
    EMPID: "Manager's Employee Id",
    EMPID_VALID: "Please enter the Manager's Employee Id (required**)",
    EMAIL: "Email Address",
    EMAIL_VALID: "Please enter the Email Id (required**)",
    DATE: "Date of Birth",
    DATE_VALID: "Please enter the date of birth (required**)",
    YOURGENDER: "Your Gender:",
    MALE: "Male",
    FEMALE: "Female",
    STOREDETAILS: "Store Details:",
    STORENAME: "Store Name",
    STORENAME_VALID: "Please enter the Store Name (required**)",
    STREET: "Street",
    STREET_VALID: "Please enter the Street (required**)",
    CITY: "City",
    CITY_VALID: "Please enter the City (required**)",
    COUNTRY: "Country",
    COUNTRY_VALID: "Please enter the Country (required**)",
    STATE: "State",
    STATE_VALID: "Please enter the State (required**)",
    ZIP: "Zip Code",
    ZIP_VALID: "Please enter the Zip Code (required**)",
    PASSWORD: "Password",
    PASSWORD_VALID: "Please enter the Password (required**)",
    CONFIRM_PASSWORD: "Confirm Password",
    CONFIRM_PASSWORD_VALID: "Please enter the correct password (required**)",
    REGISTER: "Register",
    VERIFY: "Verify",
    ENTERSIXDIGIT: "Enter Six Digit Employee ID",
    ERRORSHOULDCONTAIN: "Password must contain at least one special character (@,#),",
    ERRORSHOULDCONTAINTWO: "1 uppercase letter, 1 lowercase letter, and 1 number.",
    USEMYLOCATION: "Use My Location"
}
export const CONSTANTOTP = {
    OTPVERIFICATION: "OTP Verification",
    ENTEROTP: "Enter the OTP send to",
    DIDNOTRECEIVE: "Didn't receive OTP?",
    RESEND: "Resend OTP",
    OTPSENTAGAIN: "OTP sent again ",
    INVALIDOTP: "Invalid OTP! Try again ",
    OTPNOTENTERED: "OTP not entered "
}
export const CONSTANTLOGIN = {
    ACCELARATEHALF: "Accelarate your",
    SUSTAINABILITYHALF: "sustainability journey !!",
    PENDINGAPPOVAL: "(Your registration is still Pending for Company's approval)",
    USERNAME_VALID: "Employee Id is Required",
    PASSWORD_VALID: "Password is Required",
    REMEMBERME: "Remember me",
    FORGOTPASSWORD: "Forgot Password?",
    ENTERUSERPASSWORD: "Incorrect Employee Id or Password.",
    LOGININTOYOURACC: "Login to Account",
}
export const CONSTANTLEFTCONTENT = {
    MYCHALLENGES: "My Challenges ",
    UPCOMINGCHALLENGES: "Upcoming Challenges",
    ONGOINGCHALLENGES: "Ongoing Challenges",
    DRAFT: "draft",
    PUBLISHED: "published",
    ALLCHALLENGES: "All Challenges",
    ALL: 'all',
    UPCOMING: 'upcoming',
    ONGOING: 'ongoing',
    PARTICIPATE: 'Participate',
    MYCHALLENGE: 'My Challenges',
    HISTORICAL: 'historical',
    ENROLLED: 'enrolled',
    ENROLL: 'enroll',
    DEFAULTENROLL: "defaultenrolled",
}
export const CONSTANTRIGHTCONTENT = {
    HEADING: "My Current Ongoing Challenges",
}

export const CURRENTCONTENT = {
    VIEWMORE: 'View More',
    ENROLLNOW: 'Enroll Now',
    STARTEDON: 'Started on:',
    VIEWDETAILS: 'View Details',
    TH: "th",
    ST: "st",
    ND: "nd",
    RD: "rd",
}

export const CONSTANTFOOTERCONTENT = {
    COPYRIGHT: 'Capgemini 2022. All rights reserved.',
}

export const CONSTSTOREHOME = {
    SELECTCOUNTRY: 'Select Country',
    SELECTSTATE: 'Select State',
    SEARCH: 'Search',
    LOGOUT: 'Logout',
}

export const CONSTANTVIEWMOEWCHALLENGEDETAILS = {
    PACKAGEPERILCHALLENGE: "Package Peril Challenge",
    DELETEDIALOGSURETODELETE: "Are you sure you want to delete this challenge?",
    DELETECHALLNGE: "This will delete this challenge permanently, You can not undo this action",
    CANCEL: "Cancel",
    DELETE: "Delete",
    ENROLLNOW: "Enroll Now",
    STARTEDDATE: "Started on: 1st January 2023",
    DURATION: "Duration: 3 months (31st March 2023)",
    DESCRIPTION: "Description:",
    EVALUATIONKPI: "Evaluation KPI:",
    AMOUNT: " Amount of packaging purchased per $ sales",
    ELIGIBILITY: "Eligibility:",
    DATAREQ: "Data Required:",
    ENTERMADEBY: " Entry Made By:",
    AWARDS: "Awards:",
    WINNERSTORE: " Winner store ( trophy, featured in global ad campaign, XX USD)",
    ONESTRUNNERUP: "1st runner up ( Trophy, XX USD)",
    TWONDRUNNERUP: "2nd runner up ( Trophy, XX USD)",
    UPDATETHECHALLENGE: "Update the Challenge",
    CHALLENGEDETAILS: "Challenge Details",
    PACKAGING: "Packaging waste makes 30% of the US total waste annually with recycle rate of only 9%.Reducing packaging waste is one of the priorities area for Subway as a way to give back to the environment. Participating stores will have to think of and apply ways to reduce packaging waste in their respective stores"
}
export const CONSTANTCREATENEWCHALLENGE = {
    CREATECHALLENGE: "Create New Challenge",
    ENTERCHALLENGENAME: "Enter the Challenge Name:",
    PLEASEENTERCHALLENGENAME: "Please enter the Challenge Name",
    PLEASEENTERTHEDESCRIPTION: "Please enter the Description",
    PLEASEENTERTHEEVALUATIONKPI: "Please enter the Evaluation KPI",
    PLEASEENTERTHEELIBILTY: "Please enter the Eligibility",
    ENTERMADEBY: "EntRY Made By:",
    PLEASEENTRYMADEBY: "Please select entry type.",
    PLEASEENTERTHEDATA: "Please enter the Data ",
    PLEASEENTERTHEAWARDS: "Please enter the Awards",
    STARTDATE: "Start Date:",
    PLEASEENTERTHESTARTDATE: "Please enter the Start Date",
    THISFIELDISREQUIRED: "This field is Required.",
    STARTDATENOTVALID: "Start Date is not valid",
    ENDDATE: "End Date:",
    WINNERANNOUNCEDATE: "Winner Announcement Date:",
    SAVEDRAFT: "Saved Draft",
    PUBLISH: "Published",
    ENROLLED: "Enrolled",
    DEFAULTENROLLED: "defaultenroll",
    DEFAULTENROLL: "Default enrolled",
    DRAFT: "draft",
    DAYS: "Days",
    PUBLISHED: "published",
    ENROLL: "enrolled",
    WINNER: "Winner:",
    FIRSTRUNNERUP: "1st Runner Up:",
    SECONDRUNNERUP: "2nd Runner Up:",
    ENTRYMADEBY: "Entry Made By:",
    PLEASEENTERTHEENDDATE: "Please enter the End Date",
    PLEASEENTERTHEWINNERDATE: "Please enter the Winner Annoucemnet Date",
    ENDDATENOTVALID: "End Date is not valid",
    CLEAR: "Clear",
    UPDATE: "Update",
    WINNERDATEERROR: "Winner Annoucement Date should be after or same as End Date",
}
export const FORGOTPASSWORD = {
    FORGOTPASSWORDL: 'Forgot Password?',
    PLEASEENTER_REG_EMPID: "Please Enter your registered Email ID",
    PLEASEENTER_VERCODE: "Please Enter the verification code",
    WEHAVESENT: "We have sent a verification code to your registered email ID",
    WEWILLSEND: "We will send a verification code to your registered email ID",
    EMAILIDNOTVALID: "Email Id is not Valid",
    NEXT: "Next",
    DONE: "Done",
    PLEASEENTERSIX: "Please enter correct Email ID",
    PLEASEENTEROTP: "Please enter valid OTP ",
    PLEASEENTERPASSWORD: "Please enter a new Password",
    ENTERANEWPASSWORD: "Please enter a new Password (required**)",
    PLEASEENTERALLFIELDS: "Please fill up all Fields",
    PLEASEENTERAGAIN: "Please re-enter the password (required**)",
    CHANGEPASSWORD: "Change Password",
    PASSWORD: "Please enter a password (required**)",
    PASSWORD2: `Password should be at least 8 characters long`,
    PASSWORD3: `Password must contain at least one special character (@,#), 1 uppercase letter, 1 lowercase letter, and 1 number.`,
    REGCNFPASSWORD: `Password does not match`,
    REGCNFPASSWORDEMPTY: `Please re-enter the password (required**)`,
}
export const CONSTANTFORMCONTAINER = {
    FILLDATA: "Fill Today's Data",
    SEEHISTORY: "See History",
    SAVINGSPERWEEK: "Savings (%) per week",
    PROGRESS: "Progress",
    BACK: 'Back',
    SUBMITDATA: 'Submit Data',
    CLEAR: 'Clear',
    ERRMSG: 'This field is Required.',
    ENTERTODAYSALES: `Enter Today's Sales`,
    ENTERAMNTPURCHSED: 'Enter Amount of Packaging Purchased',
    ENDINGDATA: 'Challenge Ending On :',
    CHALLENGEDETAILS: 'Challenge Details',
    MYPROGRESS: 'My Progress',
    DOLLAR: 'Dollar',
    CO2: 'CO2',
    WASTESAVINGS: 'Waste Savings',
    MAPVIEW: 'Map View',
}
export const NOTIFICATIONBODY = {
    NOTIFICATION: "Notifications",
    MARKASALLREAD: "Mark as all read",
    NEWCHALLENGELAUNCHED: "New Challenge launched",
    ENROLLEDTHE: "Enrolled the",
    HASREGISTERED: "has registered in your store.",
    APPROVE: "Approve",
    DECLINE: "Decline",
}
export const CONSTANTPROFILE = {
    PHOTOUPLOAD: "Photo uploaded successfully!",
    PHOTOFAILED: "Photo upload failed.",
    SUCCESS: "Success",
    ERROR: "Error",
    PERSONALDETAILS: "Personal Details",
    FIRSTNAME: "Name",
    EMAILADDRESS: "Email address",
    EMPLOYEEID: "Employee Id",
    STOREID: "Store Id",
    MILLION: "Million",
    DOLLARSAVINGS: "$ Savings",
    TONNS: "tonns",
    WASTESAVINGS: " Waste Savings",
    CO: "CO",
    TWO: "2",
    LOADING: "Loading...",
    SAVINGS: "Savings",
    MYSAVINGS: "My  Savings",
    MYPROGRESS: "My Progress",
    MYCHALLENGES: "My Challenges",
    COMPLETEDCHALLENGES: "Completed Challenges",
    ONGOINGCHALLENGES: "Ongoing Challenges",
    PROFILEPAGE: "Profile Page",
    DASHBOARD: "Dashboard",
}

export const CONSTANTCHALLENGEOVERVIEW = {
    SELECTFIELD: "select the fields",
    SELECTXAXIS: "Select the X-Axis",
    SELECTYAXIS: "Select the Y-Axis",
    SELECTVALUE: "Select the Value",
    FIELD: "Field",
    XAXIS: "X-Axis",
    YAXIS: "Y-Axis",
    VALUE: "Value",
    CHARTS: 'Charts',
    PREVIEW: 'Preview',
    SAVE: 'Save',
    STACKEDCOLOPEN: 'stackedColOpen',
    STACKEDHORZOPEN: 'stackedHorzOpen',
    CHALLENGEOVERVIEW: 'Challenge Overview',
}
export const MAPVIEWS = {
    MAPVIEW: "Map View",
    RED: "red",
    GREEN: "green",
    COUNTRYNAME: 'countryname',
    STATENAME: 'statename',
}

export const CONSTANTDASHBOARD = {
    BACK: 'Back',
    PACKAGING_PERIL_CHALLENGE: 'Packaging Peril challenge',
    CHALLENGE_DETAILS: 'Challenge Details',
    MAP_VIEW: 'Map View',
    CHALLENGE_OVERVIEW: 'Challenge Overview',
    CHARTS: 'Charts',
    FIELD: 'Field',
    DATA_TYPE: 'Data Type',
    VALUE: 'Value',
    DOLLAR_SAVING: 'Dollar Saving',
    WEEKLY: 'Weekly',
    ALL_STORE: 'All Store',
    SAVE: 'Save',
    SHOW_LEADERBOARD: 'Show Leaderboard',
    CARBON_SAVING: 'Carbon Saving',
    WASTE_SAVING: 'Waste Saving',
    DOLLAR_SAVING_MILLION: '100 million',
    CARBON_SAVING_T: '100 t',
    WASTE_SAVING_T: '100 t',
    POWERED_BY_ETAP: 'Powered by ETAP',
    COPYRIGHT: '© Capgemini 2022. All rights reserved.'
}